---
title: "Codes"
output:
  pdf_document: default
  html_document: default
  word_document: default
date: "2022-12-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Only  i will write the codes, she explaned about how to connect Rstudio with Git.

How to call library:
```{r echo=TRUE}
library(ggplot2)
library(tinytex)

"how to call function in Library"

"to get working directoy:"
getwd()
"اقدر اكتب بالعربي"
"في نفس الشنك فيه يمين فوق علامه اعدادات فيها خيارات اتحكم في الشنك"
"عدلتها من اعدادت الشنك اني اخليها ينفذ الكود و يظهر لي المخرجات"

```

```{r}
"if i writr like this: ##some thing, the text will be bigger in Knit"

"numberical: 12.5
integer : 5
string: حروف
factor: male
logical: True,false"


```


```{r}
x <- 5
typeof(x)
y <- "Omar"
typeof(y)

A <- "55"
typeof(A)

is.character(y)
is.double(y)
Q <- FALSE
typeof(Q)
w <- 2/0

w


```
# use c , type of, 

```{r}
v <- c(1,2.5,4,6)
typeof(v)

M <- c(2.2,3,"A","b")
typeof(M)
"الأولويه للأسترنج"

DS <- c(TRUE,3,7.2)
typeof(DS)

```
# sequence data and using ?,?? fro exploaring libraryes
```{r}
"عشان اعرف عن مكتبه و طريقه استخدامها لازم اكتب استفهام و اسم المكتبه  في الكونسول الي تحت هذي النافذه"
?seq
??seq


DSD <- seq(1:20)
FDS <- seq(4,20, by=2)


```
#change the data type
```{r}
x
typeof(5)
"the below code make me able to change the data type from double to integer, just use: as.type of data i want"
as.integer(x)

Dateee <- 1-1-2023
typeof(Dateee)
as.character.Date(Dateee)
as.Date(Dateee)
```

#explain
```{r}

"
3**9 :
ثلاثه اوس تسعه
Sqrt(9) = 3 :
الجذر
3+3*5 = 18
هنا الاولوليه للضرب
اذا حاب اجمع او ف اسوي كذى:
(3+5)*3
-
Titoruial ((تدريب عملي من نفس الار ستوديو ، يكون محله جمب المتغيرا الي نعرفه فوق يمين

"

```

#explain
```{r}
"here pacage: it is make me able to open my project from multible devices with out mistakes in working directory
"


```

##import data
```{r}
library(tidyverse)
library(here)
```

```{r}
read_csv(here("data","SAFI_clean.csv"))
Datafile <- read.csv(here("data","SAFI_clean.csv"), na = "NULL")

```

```{r}
Datafile %>% typeof(Datafile,interview_date)
"data type:"
glimpse(Datafile)

Datafile$no_membrs

no_of_member <- Datafile$no_membrs

view(no_of_member)
"showed what is unique in the data"
unique(no_of_member)
unique(Datafile)

"length: show as number how many unique value:"
length(unique(no_of_member)) 
length(unique(Datafile))

Datafile %>% 
  select(village,no_membrs, months_lack_food)

Only <- Datafile %>% 
  select(village,no_membrs, months_lack_food)
"this code below with -c means delet the selected data"
delet_few <- Datafile %>% 
  select(-c(village,no_membrs))

"this code below with -c means delet the selected data, using : to select From .. To .."

delet_few_fwe <- Datafile %>% 
  select(-c(village:no_membrs))
"using select with filter to chose what i need from the dataset"
SSelect <- Datafile %>% 
  select(village:years_liv) %>% 
  filter(village == "God",
         years_liv > 24)

Datafile$village=="God"

```

```{r}
samlldata <- Datafile %>% 
  select(village:respondent_wall_type,rooms) %>% 
  filter(village == "God" & rooms > 1 )


Task <- Datafile %>% 
  select(memb_assoc,affect_conflicts,liv_count,no_meals) %>% 
  filter(memb_assoc == "yes")

filter(Datafile, memb_assoc == "yes")
```
```{r}
"mutate to generat a new column with our needs from the data"

Datafile %>% 
  mutate(pepole_per_room = no_membrs / rooms)

"
it is function that change the number to integer:
round()
"
newd1<- Datafile %>% 
  mutate(pepole_per_room = round(no_membrs / rooms))

```

```{r}
"
this function showed to me the NA using factr yes or no
is.na(data$the_column_name)
TRUE= NA, FALSE = Real value
"

is.na(Datafile$memb_assoc)
"to delete missing vlaue"

misss <- Datafile %>% select(memb_assoc)

clean_miss <- misss %>% select(memb_assoc) %>% 
  filter(!is.na(memb_assoc))
"
if i used is.na with out ! = it will delete the real value and keep missing value"


```

```{r}
"after cleaning"
after_clean_and_filter<- Datafile %>% 
  filter(!is.na(affect_conflicts)) %>% 
  mutate(pepole_per_room = round(no_membrs / rooms))
"i will see the data in after_clean_and_filter less than the original data becuse i delet the missing value and the result for the filter is right."



```


```{r}
after_clean_and_filter <- after_clean_and_filter %>% 
  mutate(Total_meal = no_membrs * no_meals) %>% 
  filter(Total_meal > 20)

after_clean_and_filter

view(after_clean_and_filter)

"another way to write mutate"

grouped <- Datafile %>% 
  group_by(village) %>% 
  summarise(mean = mean(no_membrs), max= max(no_membrs)) %>% 
  ungroup()

view(grouped)
```


```{r}
"code from me: How to creat data in table with spesific values"
dff <- data.frame(
  Name = c ("a", "B", "C"),
  Age = c (5, 42, 37)
)

```
```{r}
"Usualy we use summary after group by"
Datafile %>%
  group_by(no_meals) %>% 
    summarise(count = n())



Datafile %>%
  group_by(no_meals) %>% 
    count()

```

import ggplot
```{r}
library(ggplot2)
```
# ggplot
```{r}
ggplot(Datafile, aes(x=no_of_member, y=no_of_member))+
  geom_point() +
  geom_smooth() +
  facet_wrap(~) +
  coord_flip() +
  theme(legend.position = "none")

Datafile
```

#Data from R studio to train
```{r}
data()
```

```{r}
install.packages("gapminder")
library(gapminder)
gapminder
```
```{r}
gapData <- gapminder
```
#import the data from the web
```{r}
ca <- read_csv("https://raw.githubusercontent.com/scienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/ca.csv")
ca
```
#exploaring data method
```{r}
glimpse(ca)
str(ca)
```
#st plot
```{r}
ggplot(
  
  ca, aes(x=year, y= visitors, colour = park_name, size =region )
) +
  geom_point(alpha = 0.5) +
  geom_smooth() +
  theme(legend.position = "none") +
  labs(x="year", y="visitors", title="Californai national park visitation")+
  theme_minimal() +
  theme(
    legend.title = element_blank()
    
  )
```

```{r}
ggplot(
  
  ca, aes(x=year, y= visitors, colour = park_name, size =region )
) +
  geom_smooth() +
  facet_wrap(~ code, scales = "free") + 
  theme_bw()
```

```{r}
"R studio dral with arabic languge with xlsx bettwe than csv"

ca$state
unique(ca$state)
"اضافه اسم الي ملف الى ملف 
ignor
في خانه الملفات يمين تحت يخليه ماينرفع الى الجت هب حتى لو سويت كوممت"

```

