---
title: "Sessions6_AZZA"
author: "AZZA ABDULLAH S. ALGHAMDI"
date: '2022-07-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

```{r}
library(tidyverse)
library(here)

```

```{r}

interviews <- read_csv(here("data","SAFI_clean.csv"), na = "NULL")

```

```{r}

glimpse(interviews)

wall_type <- interviews$respondent_wall_type

length(unique(wall_type))

```

## Select and Filter the Data

```{r}

small_data1 <- interviews %>% 
  select(village:respondent_wall_type, rooms) %>% 
  filter(village == "God" & rooms > 1) 

```

```{r}

small_data2 <- interviews %>% 
  select(memb_assoc,affect_conflicts,liv_count,no_meals) %>%
  filter(memb_assoc == "yes")

```

```{r}

small_data3 <- interviews %>% 
mutate(total_meals = no_meals * no_membrs) %>% 
filter(total_meals > 20)

```

```{r}

data <- interviews %>%
  select(affect_conflicts, memb_assoc, liv_count, no_meals) %>%
  filter(memb_assoc == "yes")

```

```{r}

small_data4 <- interviews %>%
  mutate(people_per_room = round(no_membrs / rooms))

```

```{r}

x <- interviews %>%
  filter(!is.na(affect_conflicts)) %>%
  mutate(people_per_room = round(no_membrs / rooms))

```

```{r}

groupd <- interviews %>%
  group_by(village) %>%
  summarise(mean(no_membrs))
  ungroup() 

```


