---
title: "session5_buthynah"
author: "buthynah"
date: '2022-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(here)
```
```{r}
interviews <- read.csv(here("data","SAFI_clean.csv"), na = "NULL")
```
```{r}
glimpse(interviews)
wall_type <- interviews$respondent_wall_type
```


```{r}
length(unique(wall_type))
```
```{r}
small_data <- interviews %>% 
  select(village:respondent_wall_type,rooms) %>% 
  filter(village=="God",rooms>1)
```
```{r}
small_data2 <- interviews %>%
  mutate(people_per_room = round(no_membrs / rooms))
```


```{r}
small_data1 <- interviews %>% 
  select(affect_conflicts , liv_count , no_meals , memb_assoc) %>% 
  filter(memb_assoc=="yes")
```
```{r}
small_data3 <- interviews %>%
  filter(!is.na(affect_conflicts))
```


```{r}
small_data4 <- interviews %>%
  mutate(total_meals = no_membrs * no_meals) %>%
filter(total_meals>20)
```
```{r}
small_data5 <- interviews %>%
  group_by(village) %>%
  summarise(mean(no_membrs))
```

```{r}
small_data6 <- interviews %>%
  group_by(no_meals) %>%
summarise(no_meals=n())
  
```


