---
title: "Session5_Batool"
author: "Batool Almarzouq"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

```{r}

library(tidyverse)
library(here)

```

```{r}

interviews <- read_csv(here("data","SAFI_clean.csv"), na = "NULL")

```

## Look further into the data

```{r}
glimpse(interviews)

wall_type <- interviews$respondent_wall_type

length(unique(wall_type))

```

## Select and Filter the Data

```{r}

small_data <- interviews %>%
  select(village:respondent_wall_type, rooms) %>% 
  filter(village == "God" & rooms > 1)
  
```

```{r}

data <- interviews %>% 
  select(affect_conflicts, memb_assoc,liv_count, no_meals) %>% 
  filter(memb_assoc == "yes") 


```


```{r}

filter(memb_assoc == "yes")

```

```{r}

small_data <- interviews %>% 
  mutate(people_per_room = round(no_membrs / rooms))

```



```{r}
x <- interviews %>% 
  filter(!is.na(affect_conflicts)) %>% 
  mutate(people_per_room = round(no_membrs / rooms))

```

```{r}

interview_total_meals <- interviews %>% 
  mutate(total_meals = no_membrs * no_meals) %>% 
  filter(total_meals > 20)

```

```{r}

interview_total_meals <- mutate(interviews, total_meals = no_membrs * no_meals)

y  <- filter(interview_total_meals, total_meals > 20)

```


```{r}

grouped <- interviews %>% 
  group_by(village) %>% 
  summarise(mean = mean(no_membrs), max(no_membrs)) %>% 
  ungroup()

```

How many households in the survey have an average of two meals per day? Three meals per day? Are there any other numbers of meals represented?

```{r}
interviews %>%
  group_by(village) %>%
  summarize(
      mean_no_membrs = mean(no_membrs),
      min_no_membrs = min(no_membrs),
      max_no_membrs = max(no_membrs),
      n = n()
  )

```

```{r}
interviews %>%
  group_by(village) %>%
  summarise(
      mean_no_membrs = mean(no_membrs),
      min_no_membrs = min(no_membrs),
      max_no_membrs = max(no_membrs),
      count = n()
  )

```

```{r}
interviews %>%
  group_by(village) %>% 
  summarise(mean = mean(no_membrs))
```

```{r}

interviews %>%
  group_by(village) %>% 
  count()
```

```{r}

interviews %>%
  group_by(no_meals) %>%
  summarise(
      count = n()
  )
```

```{r}

interviews %>%
  group_by(no_meals) %>%
  count()
```
```{r}

interview_meals_summ <- interviews %>% 
  group_by(no_meals) %>% 
  summarise(
    count = n()
  )


interview_meals_count <- interviews %>% 
  group_by(no_meals) %>% 
  count()

```

